---
name: Create-> Release
# yamllint disable rule:line-length

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version for the release'
        required: true
            
jobs:
  create_release:
    runs-on: ubuntu-latest


    steps:
      - name: Get current date and time
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%dT%H-%M-%SZ')" >> $GITHUB_OUTPUT

      - name: Display date/time in output (forensics when triaging issues)
        run: echo ${{ steps.datetime.outputs.datetime }}

      - name: Check out code
        uses: actions/checkout@v3.6.0
      
      - name: Create release branch
        run: |
          git checkout -b "release/${{ inputs.version }}"
          git push origin "release/${{ inputs.version }}"

      - name: Create release through github cli
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ inputs.version }} --title ${{ inputs.version }} --generate-notes